project_name: rcon-cli
before:
  hooks:
    - go mod download
release:
  github:
    owner: itzg
    name: rcon-cli
builds:
- goos:
  - linux
  - darwin
  goarch:
  - "386"
  - amd64
  - arm
  - arm64
  goarm:
  - "6"
  - "7"
  main: .
  binary: rcon-cli
  env:
    - CGO_ENABLED=0
archives:
  -
    format: tar.gz
    rlcp: true
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
      .Arm }}{{ end }}'
    files:
    - LICENSE*
    - README*
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
dockers:
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-amd64"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-ubuntu-amd64"
    dockerfile: Dockerfile.ubuntu
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-arm64"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-ubuntu-arm64"
    dockerfile: Dockerfile.ubuntu
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-armv7"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: arm
    goarm: '7'
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - image_templates:
      - "itzg/rcon-cli:{{ .Version }}-ubuntu-armv7"
    dockerfile: Dockerfile.ubuntu
    use: buildx
    goos: linux
    goarch: arm
    goarm: '7'
    build_flag_templates:
      - "--platform=linux/arm/v7"
docker_manifests:
  - name_template: "itzg/rcon-cli:latest"
    image_templates:
      - "itzg/rcon-cli:{{ .Version }}-amd64"
      - "itzg/rcon-cli:{{ .Version }}-arm64"
      - "itzg/rcon-cli:{{ .Version }}-armv7"
  - name_template: "itzg/rcon-cli:{{ .Version }}"
    image_templates:
      - "itzg/rcon-cli:{{ .Version }}-amd64"
      - "itzg/rcon-cli:{{ .Version }}-arm64"
      - "itzg/rcon-cli:{{ .Version }}-armv7"
  - name_template: "itzg/rcon-cli:{{ .Version }}-ubuntu"
    image_templates:
      - "itzg/rcon-cli:{{ .Version }}-ubuntu-amd64"
      - "itzg/rcon-cli:{{ .Version }}-ubuntu-arm64"
      - "itzg/rcon-cli:{{ .Version }}-ubuntu-armv7"
